
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 21;
  public static final int coma = 7;
  public static final int flecha = 10;
  public static final int conjuntoDec = 22;
  public static final int porcentaje = 8;
  public static final int conj = 17;
  public static final int num = 20;
  public static final int caracter = 18;
  public static final int guion = 9;
  public static final int punto = 12;
  public static final int igual = 2;
  public static final int bor = 13;
  public static final int EOF = 0;
  public static final int puntocoma = 6;
  public static final int colocho = 11;
  public static final int error = 1;
  public static final int asterisco = 14;
  public static final int mas = 15;
  public static final int interrogacion = 16;
  public static final int llavec = 4;
  public static final int llavea = 3;
  public static final int dospuntos = 5;
  public static final int identificador = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "igual",
  "llavea",
  "llavec",
  "dospuntos",
  "puntocoma",
  "coma",
  "porcentaje",
  "guion",
  "flecha",
  "colocho",
  "punto",
  "bor",
  "asterisco",
  "mas",
  "interrogacion",
  "conj",
  "caracter",
  "identificador",
  "num",
  "cadena",
  "conjuntoDec"
  };
}

